-- Create registrations table for Noor Al Imaan
CREATE TABLE IF NOT EXISTS registrations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    
    -- Personal Information (Afaan Oromo/Amharic)
    full_name_oromo TEXT,
    age_oromo INTEGER,
    city_oromo TEXT,
    gender_oromo TEXT,
    village_oromo TEXT,
    mosque_oromo TEXT,
    phone_oromo TEXT,
    
    -- Personal Information (English/Amharic)
    full_name_english TEXT,
    age_english INTEGER,
    city_english TEXT,
    gender_english TEXT,
    village_english TEXT,
    mosque_english TEXT,
    phone_english TEXT,
    
    -- Participation Options
    participation_idea BOOLEAN DEFAULT FALSE,
    participation_money BOOLEAN DEFAULT FALSE,
    participation_material BOOLEAN DEFAULT FALSE,
    participation_provision BOOLEAN DEFAULT FALSE,
    participation_all BOOLEAN DEFAULT FALSE,
    
    -- Metadata
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Create index for better query performance
CREATE INDEX IF NOT EXISTS idx_registrations_created_at ON registrations(created_at DESC);

-- Enable Row Level Security (RLS)
ALTER TABLE registrations ENABLE ROW LEVEL SECURITY;

-- Create policy for allowing insertions
CREATE POLICY "Allow insertions" ON registrations
    FOR INSERT WITH CHECK (true);

-- Create policy for allowing select operations
CREATE POLICY "Allow select operations" ON registrations
    FOR SELECT USING (true);

-- Create policy for allowing updates
CREATE POLICY "Allow updates" ON registrations
    FOR UPDATE USING (true);

-- Create policy for allowing deletions
CREATE POLICY "Allow deletions" ON registrations
    FOR DELETE USING (true);
